# Generated by Django 4.1.7 on 2023-04-30 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_paystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(verbose_name='userId')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('ORDERID', models.CharField(max_length=30, verbose_name='ORDER ID')),
                ('amount', models.CharField(max_length=30, verbose_name='AMOUNT')),
                ('orderSTATUS', models.CharField(default='process', max_length=12, verbose_name='STATUS')),
                ('DATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
            ],
        ),
    ]
